/* Generated by tex3ds */
#pragma once

#define icons_gen_textformat_3x_idx 0
#define icons_gen_moon_fill_3x_idx 1
#define icons_gen_bolt_fill_3x_idx 2
#define icons_gen_sun_glass_3x_idx 3
#define icons_gen_badge_a_3x_idx 4
#define icons_gen_badge_b_3x_idx 5
