/* Generated by tex3ds */
#pragma once

#define ui9_gen_card9_3x_idx 0
#define ui9_gen_focus9_3x_idx 1
#define ui9_gen_pill9_3x_idx 2
#define ui9_gen_shadow9_3x_idx 3
#define ui9_gen_glow_radial_3x_idx 4
#define ui9_gen_check_3x_idx 5
#define ui9_gen_ring9_3x_idx 6
